export const navLinksdata=[
    {
        _id:1001,
        title:"Home",
        Link:"home",
    },
    {
        _id:1002,
        title:"Features",
        Link:"features",
    },
    {
        _id:1003,
        title:"Project",
        Link:"project",
    },
    {
        _id:1004,
        title:"Resume",
        Link:"resume",
    },
    {
        _id:1005,
        title:"Testimonial",
        Link:"testimonial",
    },
    {
        _id:1006,
        title:"Contacts",
        Link:"contacts",
    }
]